### Image augmentation

In [1]:
import cv2
import numpy as np
import os

In [5]:
img = cv2.imread(r"C:\Users\HARSHITHA\Downloads\cat1.jpg")

In [6]:
img.shape

(614, 900, 3)

### Translation

In [38]:
# translation matrix
tx=50
ty=50
t_m=np.array([[1,0,tx],[0,1,ty]],dtype=np.float32)

t_img = cv2.warpAffine(img,t_m,(900,614),borderMode=cv2.BORDER_CONSTANT,borderValue=(0,0,255))
t_img1 = cv2.warpAffine(img,t_m,(900,614),borderMode=cv2.BORDER_REFLECT)

In [39]:
t_m

array([[ 1.,  0., 50.],
       [ 0.,  1., 50.]], dtype=float32)

In [40]:
cv2.imshow("o_i",img)
cv2.imshow("t_i",t_img)
cv2.imshow("t_i1",t_img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [41]:
img.shape

(614, 900, 3)

In [43]:
900//2

450

### Rotation

In [56]:
r_m = cv2.getRotationMatrix2D((307,450),90,1)

In [57]:
r_m

array([[ 6.123234e-17,  1.000000e+00, -1.430000e+02],
       [-1.000000e+00,  6.123234e-17,  7.570000e+02]])

In [58]:
r_img = cv2.warpAffine(img,r_m,(900,614))

In [59]:
cv2.imshow("o_i",img)
cv2.imshow("r_img",r_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [65]:
r_m = cv2.getRotationMatrix2D((0,0),10,1)
r_img1 = cv2.warpAffine(img,r_m,(900,614))

cv2.imshow("o_i",img)
cv2.imshow("r_img",r_img1)
cv2.waitKey()
cv2.destroyAllWindows()

In [66]:
img1=cv2.rotate(img,cv2.ROTATE_180)
img2=cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
img3=cv2.rotate(img,cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("o_i",img)
cv2.imshow("r_img1",img1)
cv2.imshow("r_img2",img2)
cv2.imshow("r_img3",img3)
cv2.waitKey()
cv2.destroyAllWindows()

### Scaling  
zoom in or zoom out

In [85]:
sx=2
sy=2
tx=10
ty=10
sc_m = np.array([[sx,0,tx],[0,sy,ty]],dtype=np.float32)

In [86]:
sc_m

array([[ 2.,  0., 10.],
       [ 0.,  2., 10.]], dtype=float32)

In [87]:
img=cv2.imread(r"C:\Users\HARSHITHA\Downloads\dog1.jpg")
img.shape

(225, 225, 3)

In [88]:
scal_img = cv2.warpAffine(img,sc_m,(3*225,3*225))

cv2.imshow("o_i",img)
cv2.imshow("s_im",scal_img)
cv2.waitKey()
cv2.destroyAllWindows()

In [91]:
cv2.imshow("o_i",cv2.resize(img,(500,500)))
cv2.imshow("s_im",cv2.resize(img,(50,50)))
cv2.waitKey()
cv2.destroyAllWindows()

In [92]:
zo_o = cv2.pyrDown(img)
zo_i = cv2.pyrUp(img)

In [93]:
cv2.imshow("o_i",zo_o)
cv2.imshow("s_im",zo_i)
cv2.waitKey()
cv2.destroyAllWindows()

### Shearing

In [98]:
shx=1
shy=3
tx=0
ty=0
sh_m = np.array([[0,shx,tx],[shy,1,ty]],dtype=np.float32)

In [100]:
shear_img = cv2.warpAffine(img,sh_m,(225,225))

cv2.imshow("o_i",img)
cv2.imshow("s_im",shear_img)
cv2.waitKey()
cv2.destroyAllWindows()

### Cropping

In [2]:
img = cv2.imread(r"C:\Users\HARSHITHA\Downloads\cat1.jpg")

In [3]:
img.shape

(614, 900, 3)

In [12]:
c_i = img[130:260, 230:410]

In [13]:
cv2.imshow("o_i",img)
cv2.imshow("s_im",c_i)
cv2.waitKey()
cv2.destroyAllWindows()